# Generated by Django 5.0.9 on 2024-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(help_text='Companies this user has access to', to='company.company', verbose_name='Companies'),
        ),
    ]
