# Generated by Django 5.0.9 on 2024-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of company')),
                ('trading_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Trading Name')),
            ],
        ),
    ]
