# Generated by Django 5.0.7 on 2024-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_accounttype_active_accounttype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='accounttype',
            field=models.CharField(choices=[('S', 'Savings'), ('C', 'Cheque'), ('T', 'Transmission'), ('CU', 'Current'), ('CR', 'Credit'), ('O', 'Other')], max_length=2),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
    ]
