# Generated by Django 5.0.7 on 2024-08-06 19:40

from django.db import migrations, models
import pandas as pd
import os
from django.conf import settings


def import_city_data(apps, schema_editor):
    Country = apps.get_model('common', 'Country')
    Province = apps.get_model('common', 'Province')
    City = apps.get_model('common', 'City')
    file_path = os.path.join(settings.BASE_DIR, 'payroller', 'common', 'migrations', 'files', 'worldcities.xlsx')

    data = pd.read_excel(file_path)

    # Create a cache for countries and provinces to avoid duplicate entries
    country_cache = {}
    province_cache = {}

    # Iterate over the rows and create the corresponding objects
    for index, row in data.iterrows():
        country_name = row['country']
        province_name = row['province']

        # Handle Country
        if country_name not in country_cache:
            country, created = Country.objects.get_or_create(
                name=country_name,
                iso2=row['iso2'],
                iso3=row['iso3']
            )
            country_cache[country_name] = country
        else:
            country = country_cache[country_name]

        # Handle Province
        if (province_name, country_name) not in province_cache:
            province, created = Province.objects.get_or_create(
                name=province_name,
                country=country
            )
            province_cache[(province_name, country_name)] = province
        else:
            province = province_cache[(province_name, country_name)]

        # Handle City
        City.objects.create(
            name=row['city'],
            name_ascii=row['city_ascii'],
            latitude=row['lat'],
            longitude=row['lng'],
            province=province,
            simplemaps_id=row['id']
        )
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_country_province_city'),
    ]

    operations = [
        migrations.RunPython(import_city_data),
    ]
