# Generated by Django 5.0.7 on 2024-08-06 19:10

import common.mixins
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_alter_address_city_alter_address_line1_and_more'),
        ('employees', '0002_employee_bank_account_employee_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('uif', common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21)),
                ('sdl', common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21)),
                ('total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('uif'), '+', models.F('sdl')), output_field=common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('paye', common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21)),
                ('uif', common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21)),
                ('medical_aid', common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21)),
                ('total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('paye'), '+', models.F('uif')), '+', models.F('medical_aid')), output_field=common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('basic_salary', common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21)),
                ('commission', common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21)),
                ('total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('basic_salary'), '+', models.F('commission')), output_field=common.mixins.MoneyField(decimal_places=4, default=0.0, max_digits=21))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='common.address')),
                ('company_contributions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payslip.companycontributions')),
                ('deductions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payslip.deductions')),
                ('earnings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payslip.earnings')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
