# Generated by Django 5.0.9 on 2024-10-13 13:03

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_age', models.IntegerField()),
                ('to_age', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SarsFinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(unique=True)),
                ('month_start', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Mar', max_length=3)),
                ('month_end', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Feb', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'South African Rand')], default='ZAR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=4, max_digits=19)),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paye.agerange')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paye.sarsfinancialyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'South African Rand')], default='ZAR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=4, max_digits=19)),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paye.agerange')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paye.sarsfinancialyear')),
            ],
            options={
                'unique_together': {('age_range', 'tax_year')},
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lower_limit_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'South African Rand')], default='ZAR', editable=False, max_length=3)),
                ('lower_limit', djmoney.models.fields.MoneyField(decimal_places=4, max_digits=19)),
                ('upper_limit_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'South African Rand')], default='ZAR', editable=False, max_length=3)),
                ('upper_limit', djmoney.models.fields.MoneyField(decimal_places=4, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paye.sarsfinancialyear')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paye.taxthreshold')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
