# Generated by Django 5.0.9 on 2024-10-13 13:29

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paye', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxbracket',
            name='threshold',
        ),
        migrations.AddField(
            model_name='taxbracket',
            name='fixed_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='taxbracket',
            name='fixed_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ZAR', 'South African Rand')], default='ZAR', editable=False, max_length=3, null=True),
        ),
    ]
