# Generated by Django 5.0.9 on 2024-10-13 14:05

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paye', '0002_remove_taxbracket_threshold_taxbracket_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarsfinancialyear',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='taxbracket',
            options={'ordering': ['lower_limit']},
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='upper_limit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='upper_limit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ZAR', 'South African Rand')], default='ZAR', editable=False, max_length=3, null=True),
        ),
    ]
