# Generated by Django 5.0.7 on 2024-08-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other_names', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('rsa_id_number', models.CharField(blank=True, max_length=13, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_code', models.CharField(max_length=200)),
                ('employment_date', models.DateField()),
                ('gender', models.IntegerField(choices=[('M', 'Male'), ('F', 'Female')])),
                ('cell_no', models.CharField(max_length=20)),
                ('work_no', models.CharField(max_length=20)),
                ('pays_paye', models.BooleanField()),
                ('pays_uif', models.BooleanField()),
                ('basic_salary', models.DecimalField(decimal_places=4, max_digits=21)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
