# Generated by Django 5.0.9 on 2024-10-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_created_at_company_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other_names', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('rsa_id_number', models.CharField(blank=True, max_length=13, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=200, null=True)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], null=True)),
                ('cell_no', models.CharField(blank=True, max_length=20, null=True)),
                ('work_no', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('C', 'Cash'), ('E', 'EFT'), ('Q', 'Cheque')], max_length=2, null=True)),
                ('pays_paye', models.BooleanField(blank=True, null=True)),
                ('pays_uif', models.BooleanField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=4, max_digits=21, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
